-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 23:46:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Codigos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Codigos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Codigos` (
  `idCodigos` INT NOT NULL,
  `tamano` VARCHAR(10) NULL,
  `orientacion` VARCHAR(10) NULL,
  `precio` INT(7) NULL,
  PRIMARY KEY (`idCodigos`),
  UNIQUE INDEX `idCodigos_UNIQUE` (`idCodigos` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Formulario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Formulario` (
  `idFormulario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(65) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `codigopostal` VARCHAR(10) NOT NULL,
  `Codigos_idCodigos` INT NOT NULL,
  PRIMARY KEY (`idFormulario`),
  UNIQUE INDEX `idFormulario_UNIQUE` (`idFormulario` ASC) VISIBLE,
  INDEX `fk_Formulario_Codigos1_idx` (`Codigos_idCodigos` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Predeteminated data for ' Codigos table

INSERT INTO `` (`idCodigos`,`tamano`,`orientacion`,`precio`) VALUES (1090060,'90 cm x 60 cm','Individual',6000);
INSERT INTO `` (`idCodigos`,`tamano`,`orientacion`,`precio`) VALUES (2075070,'75 cm x 70 cm','Horizontal',9000);
INSERT INTO `` (`idCodigos`,`tamano`,`orientacion`,`precio`) VALUES (2100070,'100 cm x 70 cm','Horizontal',12000);
INSERT INTO `` (`idCodigos`,`tamano`,`orientacion`,`precio`) VALUES (2150070,'150 cm x 70 cm','Horizontal',15000);
INSERT INTO `` (`idCodigos`,`tamano`,`orientacion`,`precio`) VALUES (3075070,'75 cm x 70 cm','Vertical',9000);
INSERT INTO `` (`idCodigos`,`tamano`,`orientacion`,`precio`) VALUES (3100070,'100 cm x 70 cm','Vertical',12000);
INSERT INTO `` (`idCodigos`,`tamano`,`orientacion`,`precio`) VALUES (3150070,'150 cm x 70 cm','Vertical',15000);

